name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: '343.0.0'
          project_id: bike-rent-403120
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Build Docker Image
        run: |
          docker build -t my-flask-app .
          docker tag my-flask-app gcr.io/bike-rent-403120/my-flask-app

      - name: Configure Docker to use gcloud as a credential helper
        run: |
          gcloud auth configure-docker

      - name: Push Docker Image to Container Registry
        run: |
          docker push gcr.io/bike-rent-403120/my-flask-app

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy my-flask-app \
            --image gcr.io/bike-rent-403120/my-flask-app \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
