name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2
      with:
        project_id: bike-rent-403120
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Build and Push Docker image
      run: |
        docker build -t gcr.io/bike-rent-403120/bike-rent:$GITHUB_SHA .
        docker push gcr.io/bike-rent-403120/bike-rent:$GITHUB_SHA

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy bike-rent \
          --image gcr.io/bike-rent-403120/bike-rent:$GITHUB_SHA \
          --platform managed \
          --region us-central1  
