apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: bike-rent
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "1000"
    spec:
      containers:
        - image: gcr.io/bike-rent-403120/bike-rent:$GITHUB_SHA
          readinessProbe:
            httpGet:
              path: /hello_world
              port: 5000
